#ENC[AES256_GCM,data:4ISbJTNU2MiH04AnUNzcpEBbvG3wOQQuA+vfcPxr8B2ta7ihJq423eeR4j3mQiMhujdEU3N4F3yFuh1KO67+xiQd,iv:ZtNt4GJ5OIC3+CU7fxV1yqEEdsiG5VRFYFViLeoyefY=,tag:jqsjDR3oBULOoNTioUt78A==,type:comment]
#ENC[AES256_GCM,data:O/pp0JZGo7PVgsVzEEhFBugWqGstcMuFSDeiIndt3mfJXZG76BEX5to3Yu8lUWA=,iv:iFH+NovlHpXrpwURNgKnVKeMFJjhbQFdQqpqEBqyGK4=,tag:SoBdO4qn541sCK8xjwcjLg==,type:comment]
grafana_admin_password: ENC[AES256_GCM,data:vCR4jOmNXIfaZA==,iv:pFjCa/pkO8tDkLfNkGq5jEztV7EArqB3sVDGCqy1LgM=,tag:b57oLK6Bqfel5eblBWPfUA==,type:str]
cloudflared_tunnel_token: ""
sops:
    age:
        - recipient: age143fujxscvea9g842vqy6m59v09m63svndxsgqtc0kcm7hayttf9slwanen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5c01oKzhkUTQrWG51WVZh
            Ujc4ZnlScytBYzVrOFJwNUlYd1NiSUpxSzIwCndhUkRjcmxKMXQwRldPTDFsNnBK
            bzFRQW1jTDV1RTBTV05Lci9VcEpzejgKLS0tIGNPWXBZd3dQZlZCelBpMmJvOGRS
            T0I5cU9hSU91dTVBNHZjaEw4b0M3YWcKGrdI1OZ70SAqK1qn0epbktCepINnyv58
            +f74z/7NFx2Wd2rEnNGi1W7+yDGpxpAp026rM6DfOzFLpOWI0L15fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T18:42:36Z"
    mac: ENC[AES256_GCM,data:79QZcdz92/3AY2FMHqz1Wyfp/rEn33s4DdbwelM16gBk6MmafwqJj2yvqmEwrfNwTvkLq5wCo4IPxpEnDIS8oRGaTrBCdU5bVzuMv66Yve6NFpl7vb+C/iuuxVkWU3u6TK0UKMdLHjbHUwjRNybpZxUy/2JHKVUeIt5Gy47Xpco=,iv:s8qCWBH93t0p+oC6P5vw6skmZCj6Ph8y9GtqYKu6wNY=,tag:ZOMTtrYDzGMSw1qq3csjqA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
